### ISSUE TITLE
not hiding loading panel

### ISSUE THREAD

**Issue by rezvanshiravi** [eblondel/ol3-loadingpanel#10]
Hi 
when My map loaded completely, the loadingpanel not hiding?
I try multiple solution, but I cant solve that.
please help me to overcome this issue.

Best Regards.

**Comment by eblondel** [comment]
is your map application available online so I can have a look?

In addition, please check that all your layers are correct. You can also 
check in the chrome dev console the WMS tile requests, and see if some 
of them are still pending.

Let me know


Le 18/10/2017 à 12:44, rezvanshiravi a écrit :

**Comment by rezvanshiravi** [comment]
Thanks for quick reply.

My map is in "map.qom.ir". I check all wms tiles is loaded but loadingpanel
dont  hide yet.

**Comment by rezvanshiravi** [comment]
I forgot to mention when I click on the map, loadingpanel hides.

**Comment by eblondel** [comment]
which version of the plugin are you using?

**Comment by rezvanshiravi** [comment]
v1.0.1

**Comment by eblondel** [comment]
A precision, at this stage, loadingpanel applies to Tiled layers, if you use single tile it will not work, see #8 Please let me know if you use Tiled layers, as i can't access your app.
