### ISSUE TITLE
Compatibility with OL4

### ISSUE THREAD

**Issue by swalterfub** [eblondel/ol3-loadingpanel#7]
ol.map.beforeRender is not available in OpenLayers 4 any more. Any clue how to make it work? The error message is: `Uncaught TypeError: this.getMap(...).beforeRender is not a function`

**Comment by eblondel** [comment]
Hello @swalterfub i had a look indeed, beforeRender is not available in OL4. At first view, it's stange as beforeRender was removed to be replaced by a feature that IMHO seems to be covering only possible need behind what the potential of beforeRender. Indeed beforeRender is (was) not limited to map interactions, but let handling application events. At now, I don't know how we could handle application events at before map rendering. Maybe it is worth asking OL dev team about that.

**Comment by eblondel** [comment]
Fixed with #12
